'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace UnauthenticatedService
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="User", [Namespace]:="http://schemas.datacontract.org/2004/07/BudgeteerObjects"),  _
     System.SerializableAttribute()>  _
    Partial Public Class User
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EmailAddressField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FirstNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LastNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UserIDField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EmailAddress() As String
            Get
                Return Me.EmailAddressField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EmailAddressField, value) <> true) Then
                    Me.EmailAddressField = value
                    Me.RaisePropertyChanged("EmailAddress")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FirstName() As String
            Get
                Return Me.FirstNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FirstNameField, value) <> true) Then
                    Me.FirstNameField = value
                    Me.RaisePropertyChanged("FirstName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property LastName() As String
            Get
                Return Me.LastNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.LastNameField, value) <> true) Then
                    Me.LastNameField = value
                    Me.RaisePropertyChanged("LastName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UserID() As String
            Get
                Return Me.UserIDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UserIDField, value) <> true) Then
                    Me.UserIDField = value
                    Me.RaisePropertyChanged("UserID")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="UserSecurityQuestionAnswer", [Namespace]:="http://schemas.datacontract.org/2004/07/BudgeteerObjects"),  _
     System.SerializableAttribute()>  _
    Partial Public Class UserSecurityQuestionAnswer
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AnswerField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SecurityQuestionIDField As Long
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UserIDField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Answer() As String
            Get
                Return Me.AnswerField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AnswerField, value) <> true) Then
                    Me.AnswerField = value
                    Me.RaisePropertyChanged("Answer")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SecurityQuestionID() As Long
            Get
                Return Me.SecurityQuestionIDField
            End Get
            Set
                If (Me.SecurityQuestionIDField.Equals(value) <> true) Then
                    Me.SecurityQuestionIDField = value
                    Me.RaisePropertyChanged("SecurityQuestionID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UserID() As String
            Get
                Return Me.UserIDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UserIDField, value) <> true) Then
                    Me.UserIDField = value
                    Me.RaisePropertyChanged("UserID")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="SecurityQuestion", [Namespace]:="http://schemas.datacontract.org/2004/07/BudgeteerObjects"),  _
     System.SerializableAttribute()>  _
    Partial Public Class SecurityQuestion
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private QuestionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SecurityQuestionIDField As Long
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Question() As String
            Get
                Return Me.QuestionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.QuestionField, value) <> true) Then
                    Me.QuestionField = value
                    Me.RaisePropertyChanged("Question")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SecurityQuestionID() As Long
            Get
                Return Me.SecurityQuestionIDField
            End Get
            Set
                If (Me.SecurityQuestionIDField.Equals(value) <> true) Then
                    Me.SecurityQuestionIDField = value
                    Me.RaisePropertyChanged("SecurityQuestionID")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="UnauthenticatedService.IBudgeteerUnauthenticatedServices")>  _
    Public Interface IBudgeteerUnauthenticatedServices
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IBudgeteerUnauthenticatedServices/AddUser", ReplyAction:="http://tempuri.org/IBudgeteerUnauthenticatedServices/AddUserResponse")>  _
        Function AddUser(ByVal User As UnauthenticatedService.User, ByVal Password As String, ByVal Questions As System.Collections.Generic.List(Of UnauthenticatedService.UserSecurityQuestionAnswer)) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IBudgeteerUnauthenticatedServices/GetAvailableSecurityQuestion"& _ 
            "s", ReplyAction:="http://tempuri.org/IBudgeteerUnauthenticatedServices/GetAvailableSecurityQuestion"& _ 
            "sResponse")>  _
        Function GetAvailableSecurityQuestions() As System.Collections.Generic.List(Of UnauthenticatedService.SecurityQuestion)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IBudgeteerUnauthenticatedServices/ActivateUser", ReplyAction:="http://tempuri.org/IBudgeteerUnauthenticatedServices/ActivateUserResponse")>  _
        Function ActivateUser(ByVal userID As String, ByVal emailAddress As String, ByVal registrationKey As String) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IBudgeteerUnauthenticatedServices/GetUserSecurityQuestions", ReplyAction:="http://tempuri.org/IBudgeteerUnauthenticatedServices/GetUserSecurityQuestionsResp"& _ 
            "onse")>  _
        Function GetUserSecurityQuestions(ByVal user As UnauthenticatedService.User) As System.Collections.Generic.List(Of UnauthenticatedService.SecurityQuestion)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IBudgeteerUnauthenticatedServices/ValidateSecurityQuestions", ReplyAction:="http://tempuri.org/IBudgeteerUnauthenticatedServices/ValidateSecurityQuestionsRes"& _ 
            "ponse")>  _
        Function ValidateSecurityQuestions(ByVal user As UnauthenticatedService.User, ByVal userQuestionAnswers As System.Collections.Generic.List(Of UnauthenticatedService.UserSecurityQuestionAnswer)) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IBudgeteerUnauthenticatedServices/ResetPassword", ReplyAction:="http://tempuri.org/IBudgeteerUnauthenticatedServices/ResetPasswordResponse")>  _
        Function ResetPassword(ByVal user As UnauthenticatedService.User, ByVal userQuestionAnswers As System.Collections.Generic.List(Of UnauthenticatedService.UserSecurityQuestionAnswer), ByVal newPassword As String) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IBudgeteerUnauthenticatedServices/GetUserName", ReplyAction:="http://tempuri.org/IBudgeteerUnauthenticatedServices/GetUserNameResponse")>  _
        Function GetUserName(ByVal email As String) As String
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IBudgeteerUnauthenticatedServicesChannel
        Inherits UnauthenticatedService.IBudgeteerUnauthenticatedServices, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class BudgeteerUnauthenticatedServicesClient
        Inherits System.ServiceModel.ClientBase(Of UnauthenticatedService.IBudgeteerUnauthenticatedServices)
        Implements UnauthenticatedService.IBudgeteerUnauthenticatedServices
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function AddUser(ByVal User As UnauthenticatedService.User, ByVal Password As String, ByVal Questions As System.Collections.Generic.List(Of UnauthenticatedService.UserSecurityQuestionAnswer)) As String Implements UnauthenticatedService.IBudgeteerUnauthenticatedServices.AddUser
            Return MyBase.Channel.AddUser(User, Password, Questions)
        End Function
        
        Public Function GetAvailableSecurityQuestions() As System.Collections.Generic.List(Of UnauthenticatedService.SecurityQuestion) Implements UnauthenticatedService.IBudgeteerUnauthenticatedServices.GetAvailableSecurityQuestions
            Return MyBase.Channel.GetAvailableSecurityQuestions
        End Function
        
        Public Function ActivateUser(ByVal userID As String, ByVal emailAddress As String, ByVal registrationKey As String) As Integer Implements UnauthenticatedService.IBudgeteerUnauthenticatedServices.ActivateUser
            Return MyBase.Channel.ActivateUser(userID, emailAddress, registrationKey)
        End Function
        
        Public Function GetUserSecurityQuestions(ByVal user As UnauthenticatedService.User) As System.Collections.Generic.List(Of UnauthenticatedService.SecurityQuestion) Implements UnauthenticatedService.IBudgeteerUnauthenticatedServices.GetUserSecurityQuestions
            Return MyBase.Channel.GetUserSecurityQuestions(user)
        End Function
        
        Public Function ValidateSecurityQuestions(ByVal user As UnauthenticatedService.User, ByVal userQuestionAnswers As System.Collections.Generic.List(Of UnauthenticatedService.UserSecurityQuestionAnswer)) As Boolean Implements UnauthenticatedService.IBudgeteerUnauthenticatedServices.ValidateSecurityQuestions
            Return MyBase.Channel.ValidateSecurityQuestions(user, userQuestionAnswers)
        End Function
        
        Public Function ResetPassword(ByVal user As UnauthenticatedService.User, ByVal userQuestionAnswers As System.Collections.Generic.List(Of UnauthenticatedService.UserSecurityQuestionAnswer), ByVal newPassword As String) As Integer Implements UnauthenticatedService.IBudgeteerUnauthenticatedServices.ResetPassword
            Return MyBase.Channel.ResetPassword(user, userQuestionAnswers, newPassword)
        End Function
        
        Public Function GetUserName(ByVal email As String) As String Implements UnauthenticatedService.IBudgeteerUnauthenticatedServices.GetUserName
            Return MyBase.Channel.GetUserName(email)
        End Function
    End Class
End Namespace
